<?php /** @var \Ict\Shopbybrand\Block\Maker\Homebrand $block */
/** @var \Magento\Framework\Escaper $escaper */?>
<?php
/**
 * @author Ict Team
 * @copyright Copyright (c) 2017 Ict (http://icreativetechnologies.com/)
 * @package Ict_Shopbybrand
 */
?>
<?php if ($block->getIsFeatured()):?>
    <?php if ($block->getFullActionName() == 'cms_index_index'):?>
        <?php $_makers = $block->getMakers();?>
        <?php if (count($_makers->getData()) > 0):?>
        <div class="brand-container">
            <div class="title"><h1><?= $escaper->escapeHtml(__('Shopbybrand')) ?></h1></div>
            <div id="demo">
                <div id="owl-demo" class="owl-carousels owl-theme">
                    <?php foreach ($_makers as $_maker):?>
                        <div class="item">
                            <a href="<?= $escaper->escapeUrl($_maker->getMakerUrl());?>">
                                <img src="<?= $escaper->escapeUrl($block->getBaseUrl() . $_maker->getAvatar());?>"
                                     alt="<?= $escaper->escapeHtmlAttr($_maker->getName());?>">
                            </a>
                        </div>
                    <?php endforeach;?>
                </div>
            </div>
        </div>
        <script>
        require(['jquery', 'Ict_Shopbybrand/js/owl.carousel'], function ($) {
            $('#owl-demo').owlCarousel({
                autoPlay: 3000,
                stopOnHover: true,
                rewindNav: true,
                 rewindSpeed: 200,  
                navigation: true,
                navigationText: ['', ''],
                items: 2,
                itemsDesktop: [1199, 5],
                itemsDesktopSmall: [980, 4],
                itemsTablet: [768, 3],
                itemsMobile: [479, 2]
            });
        });
        </script>
        <?php endif;?>
    <?php endif;?>
<?php endif;?>
