<?php
/**
 * @author Ict Team
 * @copyright Copyright (c) 2017 Ict (http://icreativetechnologies.com/)
 * @package Ict_Shopbybrand
 */

/** @var \Ict\Shopbybrand\Block\Maker\ListMaker $this */
?>
<?php if ($block->isLayeredNavEnabled()): ?>
    <?php $_makers = $block->getMakers(); ?>
    <div class="shopbybrand-left">
        <strong class="block-subtitle filter-subtitle"><?= $escaper->escapeHtml(__("Shopbybrand")) ?></strong>
        <?php if ($_makers->getSize() > 0): ?>
            <ul>
                <?php foreach ($_makers as $_maker): ?>
                    <li class="brand-filter">
                        <a href="<?= $escaper->escapeUrl($_maker->getMakerUrl()) ?>">
                            <?= $escaper->escapeHtml($_maker->getName()) ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php else: ?>
            <?= $escaper->escapeHtml(__('There are no shopbybrand at this moment')) ?>
        <?php endif; ?>
    </div>
<?php endif; ?>
