<?php /** @var \Ict\Shopbybrand\Block\Maker\ViewMaker $this */?>
<?php
/**
 * @author Ict Team
 * @copyright Copyright (c) 2017 Ict (http://icreativetechnologies.com/)
 * @package Ict_Shopbybrand
 */
?>
<?php /** @var \Ict\Shopbybrand\Model\Maker $_maker */?>
<?php $_maker = $block->getCurrentMaker();?>
<?php if ($block->isBannerEnabled()) { ?>
<div class="maker-view">
    <div class="banner">
        <img src="<?= $escaper->escapeUrl($block->getBaseUrl() . $_maker->getLogobanner()) ?>">
    </div>
    <div class="banner-text">
       <p class="texts">
            <?= $escaper->escapeHtml(
                __($_maker->getBannerText()),
                ['h1','h2','h3','h4','h5','h6','p','br','strong','b','em','i','ul','ol','li','a','span','div']
            ) ?>
        </p>
    </div>
</div>
<?php } ?>